import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const Home: NextPage = () => {
  const [lang, setLang] =
    useState("en");

  const [title, setTitle] =
    useState("Hi I am");

  const [instagram, setInstagram] =
    useState(
      " a lot of random pictures ok not that lot"
    );

  const [twitter, setTwitter] =
    useState(
      " some silly quotes and memes"
    );
  const [description, setDescription] =
    useState("you can find me on");

  const setEnglish = () => {
    setLang("en");
    setTitle("Hi I am");
    setInstagram(
      "a lot of random pictures - ok not that lot"
    );
    setTwitter(
      "some silly quotes and memes"
    );
    setDescription(
      "you can find me on"
    );
  };
  const setPortuguese = () => {
    setLang("pt");
    setTitle("Oi eu sou");
    setInstagram(
      "um monte de fotos aleatórias - na verdade nem tantas"
    );
    setTwitter(
      "coisas idiotas e memes"
    );
    setDescription(
      "pode me encontrar no"
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Lua webpage</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className={styles.main}>
        <nav>
          <a
            href="#"
            onClick={setEnglish}
          >
            EN
          </a>
          <a
            href="#"
            onClick={setPortuguese}
          >
            PT
          </a>
        </nav>
        <h1 className={styles.title}>
          {title}{" "}
          <a href="https://www.instagram.com/luaarodrigues/?hl=en">
            Lua🙋🏻‍♀️
          </a>
        </h1>

        <p
          className={styles.description}
        >
          {description}{" "}
        </p>

        <div className={styles.grid}>
          <a
            href="https://www.instagram.com/luaarodrigues/?hl=en://nextjs.org/docs"
            className={styles.card}
          >
            <h2>instagram 📷</h2>
            <p>{instagram}</p>
          </a>

          <a
            href="https://twitter.com/luaaarodrigues"
            className={styles.card}
          >
            <h2>twitter 🕊️</h2>
            <p>{twitter}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
};

export default Home;
